apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: exsited-two-apps
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: builder-app
            namespace: builder-app
            path: builder-app
          - name: webhook-app
            namespace: webhook-app
            path: webhook-app
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: exsited
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      source:
        repoURL: https://github.com/M-webalive/exsited-apps.git   # public repo → HTTPS
        targetRevision: main
        path: '{{path}}'               # chart root
        helm:
          releaseName: '{{name}}'      # no valueFiles → use chart's default values.yaml
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
