apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: exsited-two-apps
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: builder-app
            namespace: builder-app
            path: builder-app
            valuesFile: values/values.yaml
          - name: webhook-app
            namespace: webhook-app
            path: webhook-app
            valuesFile: values/values.yaml
  template:
    metadata:
      name: '{{name}}'
      annotations:
        argocd.argoproj.io/sync-options: CreateNamespace=true
    spec:
      project: exsited
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      source:
        repoURL: ssh://git@github.com/M-webalive/exsited-apps.git
        targetRevision: main
        path: '{{path}}'
        helm:
          releaseName: '{{name}}'
          valueFiles:
            - '{{path}}/{{valuesFile}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
